using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace DXApplication19
{
    public partial class Form1 : DevExpress.XtraEditors.XtraForm
    {
        int n = 1;
        int m = 1;
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            //sqlDataSource1.Fill();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            string dataDir = AppDomain.CurrentDomain.BaseDirectory;
            if (dataDir.EndsWith(@"\bin\Debug\") || dataDir.EndsWith(@"\bin\Release\"))
            {
                dataDir = System.IO.Directory.GetParent(dataDir).Parent.Parent.FullName;
                AppDomain.CurrentDomain.SetData("DataDirectory", dataDir);
            }


            using (SqlConnection conn = new SqlConnection(@"server =2720FOWBH58PIRV; uid =sa; pwd =ssl19951220; database =KERN;"))
            {
                conn.Open();
                SqlDataAdapter da = new SqlDataAdapter("select * from [Table]", conn);
                DataSet ds = new DataSet();
                da.Fill(ds);

                this.chartControl1.DataSource = ds.Tables[0];
                //this.chartControl1.Series[0].DataSource = ds.Tables[0];
                //this.chartControl1.Series[1].DataSource = ds.Tables[1];
            }

            this.label1.Text = "读数据";



        }

        private void timer1_Tick(object sender, EventArgs e)
        {
            using (SqlConnection conn = new SqlConnection(@"server =2720FOWBH58PIRV; uid =sa; pwd =ssl19951220; database =KERN;"))
            {
                conn.Open();
                SqlDataAdapter da = new SqlDataAdapter("select top " + (n - m + 1) + " * from [Table1] where id not in (select top " + n + " Id from [Table1] order by Id)", conn);
                DataSet ds = new DataSet();
                da.Fill(ds);

                this.label1.Text = ds.Tables[0].Rows[0]["No"].ToString() + ":" + ds.Tables[0].Rows[0]["Result"].ToString();
                n++;
                m++;
            }

            if (this.chartControl1.DataSource != null)
            {
                this.chartControl1.DataSource = null;
            }
            else
            {
                using (SqlConnection conn = new SqlConnection(@"server =2720FOWBH58PIRV; uid =sa; pwd =ssl19951220; database =KERN;"))
                {
                    conn.Open();
                    SqlDataAdapter da = new SqlDataAdapter("select * from [Table]", conn);
                    DataSet ds = new DataSet();
                    da.Fill(ds);

                    this.chartControl1.DataSource = ds.Tables[0];

                }
            }
        }

        private void chartControl1_Click(object sender, EventArgs e)
        {

        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }
    }
}
